version: '2'
#volumes:
    #resin-data1:
services:
  app:
    build: .
    environment:
      - DEBUG
      - NODE_ENV
    hostname: 41144c1
    #container_name: service1
    # use host mode for deployment to Resin.io devices
    network_mode: host
    privileged: true
    restart: always
    #volumes:
      #- 'resin-data1:/python_balena'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.balena-socket: '1'
      io.balena.update.strategy: download-then-kill
      io.balena.update.handover-timeout: ''